version: 1

templates:
  fabric:
    name: "{minecraft}"
    loader: fabric
    mods:
      modrinth:
        - sodium

matrixes:
  - uses: fabric
    with:
      minecraft:
        - 26.1
        - 26.2
